Changed default auth for email based one
marizoldi/Erehwon pull request #67
Opened 2016-09-29 22:55 UTC by marizoldi

Updated models.py to use email/password instead of username/password (using django-custom-user).

2016-10-03 09:45 UTC, lili2311 requested changes

2016-10-03 09:45 UTC, lili2311 commented on erehwon/profiles/admin.py
> +# admin.site.register(ErehwonUser, ErehwonUserAdmin)
this is required to be present, you wont be able to see any users in the admin otherwise.

2016-10-03 09:45 UTC, lili2311 commented on erehwon/erehwon/settings/__init__.py
> +# AUTH_USER_MODEL = 'profiles.ErehwonUser'
this is commented out, it needs to be present before you run django for the "first time' for migrations and the database to be created correctly. You will probably need to drop the db again and remove all migrations.

2016-10-03 09:45 UTC, lili2311 commented on erehwon/profiles/models.py
> +from custom_user.models import AbstractEmailUser
This is imported and never used on a model, you user is not of email auth type

2016-10-07 10:35 UTC, marizoldi commented on erehwon/profiles/admin.py
> +# admin.site.register(ErehwonUser, ErehwonUserAdmin)
This PR is now only for django-registration, not custom_user implementation so this line is not needed.

2016-10-07 10:35 UTC, marizoldi commented on erehwon/erehwon/settings/__init__.py
> +# AUTH_USER_MODEL = 'profiles.ErehwonUser'
This PR is now only for django-registration, not custom_user implementation so ErehwonUser is not yet created.

2016-10-07 10:37 UTC, marizoldi commented on erehwon/profiles/models.py
> +from custom_user.models import AbstractEmailUser
This was left after I removed custom_user implemetation. Removed now.

2016-10-12 17:04 UTC, merged